Dev
SBOne-Kenobi/EmknBot pull request #6
Opened 2021-04-13 12:03 UTC by SBOne-Kenobi

2021-04-13 12:09 UTC, fuCtor requested changes

2021-04-13 12:09 UTC, fuCtor commented on src/main/scala/ru/codegen/emknbot/domain/EmknEvent.scala
> +sealed trait EventType
Лучше вынести в отдельный файл,  а потомков удобно заворачивать в  object
```
sealed trait EventType
object EventType {
   case object LectureType extends EventType
}
```

2021-04-13 12:09 UTC, fuCtor commented on src/main/scala/ru/codegen/emknbot/domain/EmknUser.scala
> +case class EmknUser(login: String, password: String, id: Int) // FIXME: only id: Int?
Можно и Int оставить, но я бы рекомендовал сделать следующее:
- завести package object 
- туда сложить type alias и использовать в коде только их
- для большей безопасности лучше даже  делать
```
final case class Password(value: String) extends AnyVal
```
это не создает накладных расходов (на первых лекциях было), но зато гарантирует контроль типов

2021-04-13 12:09 UTC, fuCtor commented on src/main/scala/ru/codegen/emknbot/domain/EventNotifier.scala
> +class c() {
Что это?

2021-04-13 12:11 UTC, fuCtor commented on src/main/scala/ru/codegen/emknbot/domain/UserRepository.scala
> +trait UserRepository[T[User]] {
Странный type параметр `T[User]`, что он означает в данном контексте?

2021-04-13 12:21 UTC, fuCtor commented
Так же не хватает хранилища для событий, не видно где они будут храниться.

2021-04-28 16:27 UTC, merged

2021-04-28 17:31 UTC, fuCtor commented on src/main/scala/ru/codegen/emknbot/domain/EventNotifier.scala
> +        subscribers.add(subscriber, eventType)
`subscribers.add((subscriber, eventType))` у вас же Set пар `(Subscriber, EventType)`

2021-04-28 17:31 UTC, fuCtor commented on src/main/scala/ru/codegen/emknbot/domain/EventNotifier.scala
> +        subscribers.remove(subscriber, eventType)
Аналогично

2021-04-28 17:31 UTC, fuCtor commented on src/main/scala/ru/codegen/emknbot/domain/EventNotifier.scala
> +            case (subscriber, event.eventType) => subscriber
Так не работает, нужно
`case (subscriber, t) if t == event.eventType => subscriber`

2021-04-28 17:37 UTC, IdeaSeeker commented on src/main/scala/ru/codegen/emknbot/domain/EventNotifier.scala
> +        subscribers.add(subscriber, eventType)
Всё итак работает же